version: "3"
services:
  ap:
    container_name: ap_server
    image: humble/ubuntu:22.04
# Not working
    volumes:
      - type: bind
        source: /home/hht/docker_workspace/ros2_ws
        target: /root/ros2_ws
        volume:
          nocopy: false
    network_mode: host
    ipc: host
    restart: always
    entrypoint:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        ros2 launch telecontrol_server telecontrol_server.launch.py

volumes:
  /home/hht/docker_workspace/ros2_ws:
    external: true

  # postgres:
  #   image: postgres:latest
  #   container_name: Dev-postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./script:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   network_mode: host
  #   ipc: host
  #   restart: always